buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:9.0.1'
    }
}

allprojects {

    ext {
        appName = 'Slay the Dungeon'
        appPackageName = 'com.pizenblues.pixeldungeon'
        appVersionCode = 90
        appVersionName = '1.0.1'

        appAndroidCompileSDK = 35
        appAndroidMinSDK = 21
        appAndroidTargetSDK = 35
    }
    version = appVersionName

    repositories {
        google()
        mavenCentral()
    }

}